pushing few other changes

diff --git a/.github/workflows/cxp-catalog-domain.yml b/.github/workflows/cxp-catalog-domain.yml
--- a/.github/workflows/cxp-catalog-domain.yml
+++ b/.github/workflows/cxp-catalog-domain.yml
@@ -39,27 +39,28 @@ jobs:
       - name: Build with Maven
         run: ./mvnw -ntp verify
 
-      - name: Login to Docker Hub
+      - if: ${{ github.ref == 'refs/heads/main' }}
+        name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build and Tag Docker Image
-        run: |
-          docker build --build-arg DOCKER_TAG=${{ steps.meta.outputs.tags }} --tag ${{ steps.meta.outputs.tags }} .
+      - if: ${{ github.ref == 'refs/heads/main' }}
+        name: Build and Publish Docker Image
+        run:
+          ./mvnw spring-boot:build-image -DskipTests
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/easyshop-cxp-catalog-domain
 
-      - name: Build Docker Image with Debug Logs
-        run: ./mvnw spring-boot:build-image -DskipTests
 
-      - name: Verify Docker Image
-        run: docker images | grep $DOCKER_IMAGE_NAME
-
-      - name: Push Docker Image
-        run: |
-          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
-#          docker build -t kishore465/cxp-catalog-domain:latest -f "./deployment/docker-compose/infra.yml" .
-#          docker push cxp-catalog-domain:latest || echo "Docker push failed. Verify that the image exists locally and the name is correct."
-#          docker push --all-tags $DOCKER_IMAGE_NAME || echo "Docker push failed. Verify that the image exists locally and the name is correct."
-           docker push ${{ steps.meta.outputs.tags }}
-          
+#      - name: Verify Docker Image
+#        run: docker images | grep $DOCKER_IMAGE_NAME
+#
+#      - name: Push Docker Image
+#        run: |
+#          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
+##          docker build -t kishore465/cxp-catalog-domain:latest -f "./deployment/docker-compose/infra.yml" .
+##          docker push cxp-catalog-domain:latest || echo "Docker push failed. Verify that the image exists locally and the name is correct."
+##          docker push --all-tags $DOCKER_IMAGE_NAME || echo "Docker push failed. Verify that the image exists locally and the name is correct."
+#           docker push ${{ steps.meta.outputs.tags }}
+#
