added few changes to workflow file

diff --git a/.github/workflows/cxp-catalog-domain.yml b/.github/workflows/cxp-catalog-domain.yml
--- a/.github/workflows/cxp-catalog-domain.yml
+++ b/.github/workflows/cxp-catalog-domain.yml
@@ -49,6 +49,7 @@ jobs:
       - name: Push Docker Image
         run: |
           echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
-          docker push cxp-catalog-domain:latest
-          docker push --all-tags $DOCKER_IMAGE_NAME || echo "Docker push failed. Verify that the image exists locally and the name is correct."
+          docker build -t kishore465/cxp-catalog-domain:latest
+          docker push cxp-catalog-domain:latest || echo "Docker push failed. Verify that the image exists locally and the name is correct."
+#          docker push --all-tags $DOCKER_IMAGE_NAME || echo "Docker push failed. Verify that the image exists locally and the name is correct."
           
