added few changes to workflow file

diff --git a/.github/workflows/cxp-catalog-domain.yml b/.github/workflows/cxp-catalog-domain.yml
--- a/.github/workflows/cxp-catalog-domain.yml
+++ b/.github/workflows/cxp-catalog-domain.yml
@@ -40,9 +40,14 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build and Publish Docker Image
+      - name: Build Docker Image with Debug Logs
+        run: ./mvnw spring-boot:build-image -DskipTests -X
+
+      - name: Verify Docker Image
+        run: docker images | grep $DOCKER_IMAGE_NAME
+
+      - name: Push Docker Image
         run: |
-          ./mvnw spring-boot:build-image -DskipTests
           echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
-          docker push $DOCKER_IMAGE_NAME
+          docker push $DOCKER_IMAGE_NAME || echo "Docker push failed. Verify that the image exists locally and the name is correct."
           
