added few changes to workflow file

diff --git a/.github/workflows/cxp-catalog-domain.yml b/.github/workflows/cxp-catalog-domain.yml
--- a/.github/workflows/cxp-catalog-domain.yml
+++ b/.github/workflows/cxp-catalog-domain.yml
@@ -14,20 +14,25 @@ jobs:
     runs-on: ubuntu-latest
     env:
       working-directory: ./cxp-catalog-domain
-      DOCKER_IMAGE_NAME: cxp-catalog-domain
+      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/cxp-catalog-domain
     defaults:
       run:
         working-directory: ${{ env.working-directory }}
     steps:
       - uses: actions/checkout@v4
 
-      - name: Set up JDK 17
+      - name: Set up JDK 21
         uses: actions/setup-java@v4
         with:
-          java-version: '17'
+          java-version: '21'
           distribution: 'temurin'
           cache: 'maven'
 
+      - name: Extract Docker image metadata
+        id: meta
+        uses: docker/metadata-action@v5
+        with:
+            images: ${{ vars.DOCKER_USERNAME }}/cxp-catalog-domain
       - name: Make Maven wrapper executable
         run: chmod +x mvnw
 
@@ -40,6 +45,10 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
+      - name: Build and Tag Docker Image
+        run: |
+          docker build --build-arg DOCKER_TAG=${{ steps.meta.outputs.tags }} --tag ${{ steps.meta.outputs.tags }} .
+
       - name: Build Docker Image with Debug Logs
         run: ./mvnw spring-boot:build-image -DskipTests
 
@@ -49,7 +58,8 @@ jobs:
       - name: Push Docker Image
         run: |
           echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
-          docker build -t kishore465/cxp-catalog-domain:latest -f "./deployment/docker-compose/infra.yml" .
-          docker push cxp-catalog-domain:latest || echo "Docker push failed. Verify that the image exists locally and the name is correct."
+#          docker build -t kishore465/cxp-catalog-domain:latest -f "./deployment/docker-compose/infra.yml" .
+#          docker push cxp-catalog-domain:latest || echo "Docker push failed. Verify that the image exists locally and the name is correct."
 #          docker push --all-tags $DOCKER_IMAGE_NAME || echo "Docker push failed. Verify that the image exists locally and the name is correct."
+           docker push ${{ steps.meta.outputs.tags }}
           
